# Site settings
title: Bike Living The Americas
header-img: img/home-bg.jpg
email: megan.wycklendt@gmail.com
description: "Blog for Megan Wycklendt and Gordon Dunlop"
baseurl: ""
url: "http://bikelivingtheamericas.com"
#url: "http://localhost:4000"
twitter_username: Alaska2Ushuaia
github_username: mattwycklendt
facebook_username: bikelivingtheamericas
instagram_username: bikelivingtheamericas

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 1
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "Gemfile.lock"]
