# Site settings
title: Bike Living The Americas
header-img: img/home-bg.jpg
email: mattwycklendt@gmail.com.com
description: "Blog for Megan Wycklendt and Gordon Dunlop"
#cbaseurl: "/BikeLivingTheAmericas"
url: "http://bikelivingtheamericas.com"
twitter_username: meganwycklendt
github_username: mattwycklendt
facebook_username: meganwycklendt

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
